'use strict';
const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sub=s=>{try{return ChemEngine.formatFormula(s)}catch{return String(s).replace(/[0-9]/g,n=>'₀₁₂₃₄₅₆₇₈₉'[n])}};
const elements=globalThis.Elements;
const elementMap=Object.fromEntries(elements.map(e=>[e.symbol,e]));
const stateNames={solid:'固體',liquid:'液體',gas:'氣體',aqueous:'水溶液',unknown:'資料未知'};
const colors={nonmetal:'#79e3c8',noble:'#c1a3f5',alkali:'#93bcfb',alkaline:'#8edbe2',metalloid:'#efbb7a',halogen:'#a7e6a0',transition:'#8ab8d2',post:'#82d1d9',lanthanide:'#eea1c5',actinide:'#c8a2df'};
const categories={nonmetal:'非金屬',noble:'惰性氣體',alkali:'鹼金屬',alkaline:'鹼土金屬',metalloid:'類金屬',halogen:'鹵素',transition:'過渡金屬',post:'後過渡金屬',lanthanide:'鑭系',actinide:'錒系'};
const legacyCategories={H2O:'oxides',NaCl:'salts',CO2:'gases',CH4:'organic',Fe:'elements',O2:'gases',H2:'gases',N2:'gases',NH3:'gases',MgO:'oxides',Cu:'elements',SiO2:'oxides',Fe2O3:'oxides',CaCO3:'salts',C6H12O6:'biomolecules','Ca(OH)2':'bases','CuSO4·5H2O':'salts'};
ChemData.compounds.forEach((c,i)=>{c.id||='compound-'+i;c.category||=legacyCategories[c.formula]||'other'});
ChemData.reactions.forEach(r=>{r.category||=['water','methane','carbon'].includes(r.id)?'combustion':'oxidation'});
let catalog=ChemCatalog.create(ChemData,ChemEngine);
const libraryState={query:'',category:'all',state:'all',provenance:'all',page:1};
const lab={counts:{H:2,O:1},mode:'atoms',filter:'all',selected:'O',compound:ChemData.compounds[0],formula:'H2O',reaction:null,balanced:null,library:'compounds',dirty:false,charge:0,candidates:[],reactionChoices:[],mixture:null,revision:0};
const renderer=new AtomRenderer($('molecule-canvas'));
let toastTimeout;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').hidden=true,4500)}
function tile(e){return `<button class="element-tile ${lab.selected===e.symbol?'selected':''}" data-element="${e.symbol}" style="--element-color:${colors[e.category]}" title="${e.number} ${e.name} ${e.english}；點選加入" aria-label="加入${e.name} ${e.symbol}原子"><span class="atomic-number">${e.number}</span><strong>${e.symbol}</strong><small>${e.name}</small></button>`}
function renderElements(){let query=$('element-search').value.trim().toLowerCase();let filtered=elements.filter(e=>(!query||[e.symbol,e.name,e.english,String(e.number)].some(v=>v.toLowerCase().includes(query)))&&(lab.filter==='all'||(lab.filter==='nonmetal'?['nonmetal','noble','halogen','metalloid'].includes(e.category):!['nonmetal','noble','halogen','metalloid'].includes(e.category))));$('element-grid').innerHTML=filtered.length?filtered.map(tile).join(''):'<p class="empty-copy">找不到符合的元素</p>';$('element-count').textContent=filtered.length+' / 118 ELEMENTS';renderDetail()}
function renderDetail(){let e=elementMap[lab.selected];$('element-detail').innerHTML=`<div class="detail-symbol" style="color:${colors[e.category]}">${e.symbol}</div><div><h3>${e.name}<small>${e.english}</small></h3><p>原子序 ${e.number} · ${categories[e.category]}</p><p>原子質量 ${e.mass} u</p><p>元素參考物態：${stateNames[e.state]}</p></div>`}
function compositionFormula(counts){let order=Object.keys(counts);if(order.includes('C'))order=['C',...(order.includes('H')?['H']:[]),...order.filter(s=>s!=='C'&&s!=='H').sort()];else order.sort((a,b)=>elementMap[a].number-elementMap[b].number);return order.map(s=>s+(counts[s]===1?'':counts[s])).join('')}
function matchingCompound(counts){return catalog.identify(counts)}
function resolveComposition(value){lab.candidates=catalog.candidates(value);lab.compound=catalog.identify(value)}
function sourceLink(url){return /^https:\/\//.test(url||'')?`<a class="source-link" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">查看資料來源 ↗</a>`:''}
function compoundChoices(){return lab.candidates.length>0?`<div class="candidate-list"><p>相同組成有 ${lab.candidates.length} 筆已收錄候選，請選擇物質：</p>${lab.candidates.map(c=>`<button data-compound="${c.id}"><b>${escapeHTML(c.name)}</b><span>${stateNames[c.state]}</span></button>`).join('')}</div>`:''}
function reactionChoices(){return lab.reactionChoices.length>1?`<div class="candidate-list"><p>反應條件不同，可能有不同結果：</p>${lab.reactionChoices.map(r=>`<button data-reaction="${r.id}"><b>${escapeHTML(r.name)}</b><small>${escapeHTML(r.condition)}</small></button>`).join('')}</div>`:''}
function renderChips(){let entries=Object.entries(lab.counts);$('atom-chips').innerHTML=entries.length?entries.map(([s,n])=>`<div class="atom-chip"><span>${s}</span><b>× ${n.toLocaleString()}</b>${lab.mode==='atoms'?`<button data-remove="${s}" aria-label="移除一個${elementMap[s].name}原子">−</button>`:''}</div>`).join(''):'<p class="empty-copy">點選元素，或輸入一個化學式</p>';$('atom-summary').textContent=`${Object.values(lab.counts).reduce((a,b)=>a+b,0).toLocaleString()} 顆原子 · ${entries.length} 種元素${lab.charge?' · 電荷 '+(lab.charge>0?'+':'')+lab.charge:''}`;$('combine-btn').disabled=!entries.length;$('combine-btn').hidden=lab.mode!=='atoms';$('tray-title').textContent=lab.mode==='atoms'?'實驗台上的原子':'化學式的原子組成'}
function renderResult(){
 const c=lab.compound,count=Object.values(lab.counts).reduce((a,b)=>a+b,0),formula=lab.formula||'—',known=Boolean(c)&&!lab.dirty;
 const ambiguous=!lab.dirty&&!known&&lab.candidates.length>0;
 const name=lab.dirty?'準備組合':c?.name||(ambiguous?'已收錄的可能物質':lab.formula==='e^-'?'電子':!count?'等待加入原子':'原子組成已解析');
 const state=known?c.state:'unknown',phase={solid:'s',liquid:'l',gas:'g',aqueous:'aq'}[state];
 $('result-content').innerHTML=`<div class="result-content-inner"><div class="result-kicker"><span>${lab.dirty?'READY TO COMBINE':known?'SUBSTANCE DETAILS':ambiguous?'MULTIPLE MATCHES':'COMPOSITION ONLY'}</span><span class="state-badge ${state}">${stateNames[state]}${known&&phase?' / '+phase:''}</span></div>
 <div class="result-formula ${formula.length>7?'long':''}">${escapeHTML(sub(formula))}</div><div class="result-name"><h3>${escapeHTML(name)}</h3><span>${escapeHTML(known?c.english:lab.dirty?'READY':'EXPLORE')}</span></div>
 <div class="result-equation"><small>原子組成${known&&['lattice','metal'].includes(c.model)?'（化學式單位）':''}</small>${Object.entries(lab.counts).map(([s,n])=>n+' '+s).join(' + ')||'尚未加入'}</div>
 <dl class="result-facts"><div><dt>組成元素</dt><dd>${Object.keys(lab.counts).length} 種</dd></div><div><dt>原子數合計</dt><dd>${count.toLocaleString()}</dd></div><div><dt>${known?'鍵結／結構':'結構判定'}</dt><dd>${escapeHTML(known?c.bond:'尚無足夠資料')}</dd></div><div><dt>${known?'式量 / 相對分子質量':'參考物態'}</dt><dd>${known?escapeHTML(c.mass):'未知'}</dd></div></dl>
 ${ambiguous?compoundChoices():''}<div class="insight ${known?(c.hazard==='unknown'?'warning':c.hazard||''):'warning'}"><h4>${escapeHTML(known?c.tip:lab.dirty?'按「組合原子」探索':ambiguous?'化學式不能唯一決定結構':'未知 ≠ 安全')}</h4><p>${escapeHTML(known?c.note:lab.dirty?'可以繼續加入或移除原子，再查看組成與已收錄資料。':ambiguous?'相同的原子數可以有不同的連接方式、物態或性質。選擇具體物質後，才顯示它的資料。':'此組成尚無物質與反應資料；化學式可解析，不表示物質一定存在、結構唯一，或混合後不會反應。')}</p></div>
 ${known?'<p class="result-explanation">'+escapeHTML(c.detail)+'</p>'+sourceLink(c.sourceUrl):''}</div>`;
}
function updateScene(){lab.revision++;renderer.set(lab.counts,lab.dirty?null:lab.compound);$('scene-formula').textContent=sub(lab.formula)||'＋';$('scene-name').textContent=lab.dirty?'ATOMS / 尚未組合':lab.compound?lab.compound.name+' / '+lab.compound.english:'COMPOSITION / 組成示意';renderChips();renderResult();if(lab.mode==='equation'&&lab.balanced)renderEquationResult();else if(lab.mode==='equation'&&lab.mixture)renderMixtureResult()}
function setCompound(compound){if(!compound)return;setMode('atoms');lab.counts={...compound.counts};lab.compound=compound;lab.formula=compound.formula;lab.dirty=false;lab.reaction=null;lab.balanced=null;lab.charge=ChemEngine.parseFormula(compound.formula).charge;lab.candidates=[];lab.mixture=null;lab.reactionChoices=[];updateScene();$('lab-content').scrollIntoView({behavior:'smooth',block:'nearest'})}
function addElement(symbol){if(!elementMap[symbol])return;let total=Object.values(lab.counts).reduce((a,b)=>a+b,0);if(total>=240){toast('點選模式最多 240 顆原子；更大的組成請使用化學式探索。');return}setMode('atoms');lab.counts[symbol]=(lab.counts[symbol]||0)+1;lab.selected=symbol;lab.formula=compositionFormula(lab.counts);lab.compound=null;lab.dirty=true;lab.reaction=null;lab.balanced=null;lab.charge=0;lab.candidates=[];lab.reactionChoices=[];lab.mixture=null;renderElements();updateScene();if($('periodic-dialog').open){$('periodic-dialog').close();toast(`已加入 1 個${elementMap[symbol].name}原子`)}}
function catalogFilterLabels(){return [libraryState.category!=='all'?'分類：'+(catalog.labels[libraryState.category]||libraryState.category):'',lab.library==='compounds'&&libraryState.state!=='all'?'物態：'+stateNames[libraryState.state]:'',libraryState.provenance!=='all'?'來源：'+({teaching:'中文教學',pubchem:'PubChem',rhea:'Rhea／SIB'}[libraryState.provenance]||libraryState.provenance):''].filter(Boolean)}
function catalogEmptyState(){
 const query=libraryState.query.trim(),filters=catalogFilterLabels();
 const all=catalog.query({kind:lab.library,query,pageSize:3});
 const hiddenMatches=filters.length&&all.total>0;
 const examples=all.items.map(c=>escapeHTML(c.name)+'（'+escapeHTML(catalog.labels[c.category]||'物質')+'）').join('、');
 return `<div class="catalog-empty"><h3>${hiddenMatches?'資料已收錄，被目前篩選排除了':'內建資料庫沒有符合的結果'}</h3><p>${hiddenMatches?'移除篩選後可找到 '+all.total+' 筆，例如 '+examples+'。':'可改用名稱或化學式搜尋，或前往線上資料庫查詢更多資料。'}</p>${filters.length?'<p class="catalog-filter-note">目前篩選：'+filters.map(escapeHTML).join(' · ')+'</p>':''}<div class="catalog-empty-actions">${filters.length?'<button type="button" class="accent-button" data-clear-catalog-filters>清除篩選，保留搜尋</button>':''}${!hiddenMatches&&query?'<button type="button" class="accent-button" data-search-online>帶到線上資料庫查詢</button>':''}</div></div>`;
}
function renderCards(){
 if(lab.library==='online'){$('library-summary').textContent='連線查詢 PubChem 物質與 Rhea 生化反應，結果逐筆附來源。';return}
 const result=catalog.query({kind:lab.library,...libraryState});libraryState.page=result.page;
 $('library-summary').textContent=ChemData.compounds.length+' 種物質 · '+ChemData.reactions.length+' 組反應 · 可搜尋、分類與自由探索';
 const filters=catalogFilterLabels();$('catalog-status').textContent='找到 '+result.total+' '+(lab.library==='compounds'?'種物質':'組反應')+(filters.length?' · '+filters.join(' · '):'');
 const palette=['#8ccff3','#c0a5f5','#79ddbf','#f3bb7c','#adc0d0','#8eb9ef'];
 $('experiment-cards').innerHTML=result.items.length?result.items.map((c,i)=>{const compound=lab.library==='compounds';const formula=compound?sub(c.formula):Object.keys(c.inputs).map(sub).join(' + ');return `<button class="experiment-card" data-${compound?'compound':'reaction'}="${c.id}" style="--color:${palette[i%palette.length]}"><div class="card-top"><strong>${escapeHTML(formula)}</strong><span>${compound?stateNames[c.state]:catalog.labels[c.category]||'反應'}</span></div><h3>${escapeHTML(c.name)}</h3><p>${escapeHTML(compound?catalog.labels[c.category]||'物質':c.short)}</p></button>`}).join(''):catalogEmptyState();
 $('catalog-prev').disabled=result.page<=1;$('catalog-next').disabled=result.page>=result.pages;$('catalog-page').textContent='第 '+result.page+' / '+result.pages+' 頁';
}
function configureLibrary(){const online=lab.library==='online';document.querySelector('.catalog-toolbar').hidden=online;document.querySelector('.catalog-pagination').hidden=online;$('experiment-cards').hidden=online;$('catalog-status').hidden=online;if($('online-panel'))$('online-panel').hidden=!online;const source=lab.library==='compounds'?ChemData.compounds:ChemData.reactions;const values=[...new Set(source.map(c=>c.category))];$('library-category').innerHTML='<option value="all">全部分類</option>'+values.map(v=>'<option value="'+v+'">'+(catalog.labels[v]||v)+'</option>').join('');$('library-category').value=libraryState.category; $('library-state-label').hidden=lab.library==='reactions';if($('library-provenance')){$('library-provenance').innerHTML='<option value="all">全部來源</option><option value="teaching">中文教學</option>'+(lab.library==='compounds'?'<option value="pubchem">PubChem</option>':'<option value="rhea">Rhea／SIB</option>');$('library-provenance').value=libraryState.provenance;}} 
function changeLibraryPage(delta){libraryState.page+=delta;renderCards();$('library-title').scrollIntoView({behavior:'smooth',block:'start'})}
$('library-search').addEventListener('input',()=>{libraryState.query=$('library-search').value;libraryState.page=1;renderCards()});
$('library-category').addEventListener('change',()=>{libraryState.category=$('library-category').value;libraryState.page=1;renderCards()});
$('library-state').addEventListener('change',()=>{libraryState.state=$('library-state').value;libraryState.page=1;renderCards()});
$('experiment-cards').addEventListener('click',event=>{if(!event.target.closest('[data-clear-catalog-filters]'))return;libraryState.category=libraryState.state=libraryState.provenance='all';libraryState.page=1;$('library-category').value=$('library-state').value=$('library-provenance').value='all';renderCards()});
$('catalog-prev').addEventListener('click',()=>changeLibraryPage(-1));$('catalog-next').addEventListener('click',()=>changeLibraryPage(1));
document.addEventListener('click',e=>{let el=e.target.closest('[data-element]');if(el){addElement(el.dataset.element);return}el=e.target.closest('[data-remove]');if(el){let s=el.dataset.remove;if(--lab.counts[s]<=0)delete lab.counts[s];lab.formula=compositionFormula(lab.counts);lab.compound=null;lab.dirty=true;lab.charge=0;updateScene();return}el=e.target.closest('[data-compound]');if(el){setCompound(catalog.getCompound(el.dataset.compound));return}el=e.target.closest('[data-reaction]');if(el){loadReaction(el.dataset.reaction);return}el=e.target.closest('[data-close]');if(el)$(el.dataset.close).close();if(e.target.closest('#play-reaction'))playReaction()});
$('element-search').addEventListener('input',renderElements);
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{lab.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderElements()}));
$('combine-btn').addEventListener('click',()=>{const charge=lab.charge;const formula=compositionFormula(lab.counts)+(charge?'^'+(Math.abs(charge)===1?'':Math.abs(charge))+(charge>0?'+':'-'):'');resolveComposition(charge?formula:lab.counts);lab.formula=lab.compound?.formula||formula;lab.dirty=false;updateScene();renderer.trigger('bond')});
$('clear-btn').addEventListener('click',()=>{lab.counts={};lab.compound=null;lab.formula='';lab.dirty=false;lab.reaction=null;lab.balanced=null;lab.charge=0;lab.candidates=[];lab.reactionChoices=[];lab.mixture=null;$('formula-input').value='';$('equation-input').value='';clearError();updateScene();$('effect-banner').hidden=true});
$('pause-btn').addEventListener('click',()=>{renderer.paused=!renderer.paused;syncPause()});
function syncPause(){$('pause-btn').textContent=renderer.paused?'▷':'Ⅱ';$('pause-btn').title=renderer.paused?'恢復旋轉':'暫停旋轉';$('pause-btn').setAttribute('aria-label',$('pause-btn').title);$('pause-btn').setAttribute('aria-pressed',renderer.paused)}
$('reset-view').addEventListener('click',()=>{renderer.angle=.25;renderer.tilt=-.18;renderer.zoom=1});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{renderer.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});$('scene-label').textContent=renderer.view==='matter'?'STATE OF MATTER':'MOLECULAR VIEW'}));
$('help-open').addEventListener('click',()=>$('help-dialog').showModal());
$('periodic-open').addEventListener('click',()=>{$('periodic-table').innerHTML=elements.map(e=>tile(e).replace('style="',`style="grid-column:${e.displayColumn};grid-row:${e.displayRow};`)).join('');$('periodic-dialog').showModal()});
$('sources-open').addEventListener('click',()=>$('sources-dialog').showModal());
$('sources-content').innerHTML='<p>本頁是互動教學模型。球的大小、距離、晶格和粒子運動均為示意，沒有進行量子化學或熱力學計算。</p><p>化學式解析支援 118 種元素。化學式本身不能決定物質是否存在、同分異構物、反應途徑或危險性。未知項目會保留未知。</p><p>物態以 25 °C、1 atm 為參考。104–118 號超重元素的物態標為未知；原子質量依 PubChem 資料，不等同全部元素的標準原子量。反應式配平只檢查原子與電荷守恆。</p><ul>'+ChemData.sources.map(s=>`<li><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title}</a></li>`).join('')+'</ul><p>危險反應的動畫與警示只供辨識風險，不提供實際操作條件。請勿在現實中重現。</p>';
function setMode(mode){if(!['atoms','formula','equation'].includes(mode))return;lab.mode=mode;document.body.dataset.mode=mode;$('effect-banner').hidden=true;renderer.effect=null;document.querySelectorAll('[data-mode]').forEach(b=>{let selected=b.dataset.mode===mode;b.classList.toggle('active',selected);b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1});$('lab-content').setAttribute('aria-labelledby','tab-'+mode);$('formula-form').hidden=mode!=='formula';$('equation-form').hidden=mode!=='equation';if(mode==='formula'&&!$('formula-input').value)$('formula-input').value=lab.formula;$('combine-btn').hidden=mode!=='atoms';clearError();renderChips();renderResult();if(mode==='equation'&&lab.balanced)renderEquationResult();else if(mode==='equation'&&lab.mixture)renderMixtureResult()}
document.querySelectorAll('[data-mode]').forEach(b=>{b.addEventListener('click',()=>setMode(b.dataset.mode));b.addEventListener('keydown',e=>{let modes=['atoms','formula','equation'];let i=modes.indexOf(lab.mode);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();let mode=modes[(i+(e.key==='ArrowRight'?1:2))%3];setMode(mode);$('tab-'+mode).focus()}})});
const errorBox=document.createElement('p');errorBox.id='input-error';errorBox.className='input-error';errorBox.setAttribute('role','alert');errorBox.hidden=true;$('lab-content').insertBefore(errorBox,$('viewport'));
$('formula-input').setAttribute('aria-describedby','input-error');$('equation-input').setAttribute('aria-describedby','input-error');
function clearError(){errorBox.hidden=true;errorBox.textContent='';$('formula-input').removeAttribute('aria-invalid');$('equation-input').removeAttribute('aria-invalid')}
function showError(error,input){errorBox.textContent=error.message||'無法解析，請檢查輸入內容。';errorBox.hidden=false;$(input).setAttribute('aria-invalid','true')}
function exploreFormula(input){let parsed=ChemEngine.parseFormula(input);lab.counts={...parsed.counts};lab.formula=parsed.normalized;lab.charge=parsed.charge;resolveComposition(parsed.normalized);lab.dirty=false;lab.reaction=null;lab.balanced=null;lab.mixture=null;lab.reactionChoices=[];clearError();updateScene();renderer.trigger('bond');if(parsed.totalAtoms>100)toast('組成計算完整；模型僅顯示抽樣粒子，以保持操作流暢。');return parsed}
$('formula-form').addEventListener('submit',e=>{e.preventDefault();try{exploreFormula($('formula-input').value)}catch(error){showError(error,'formula-input')}});
function equationText(result){const side=a=>a.map(s=>(s.coefficient===1?'':s.coefficient+' ')+sub(s.formula)).join(' + ');return side(result.reactants)+' → '+side(result.products)}
function identifyReaction(result,selectedId){lab.reactionChoices=catalog.findReactions(result.reactants,result.products);return selectedId?lab.reactionChoices.find(r=>r.id===selectedId)||null:lab.reactionChoices.length===1?lab.reactionChoices[0]:null}
function balanceInput(input,selectedId=null){let balanced=ChemEngine.balanceEquation(input);lab.balanced=balanced;lab.reaction=identifyReaction(balanced,selectedId);lab.mixture=null;lab.dirty=false;let product=balanced.products.find(p=>p.formula===lab.reaction?.product)||balanced.products[0];lab.formula=product.formula;lab.counts={...product.counts};lab.charge=product.charge;resolveComposition(product.formula);clearError();updateScene();return balanced}
function exploreReactionInput(input){
 if(/->|=>|→|=/.test(input))return balanceInput(input);
 const species=ChemEngine.parseReactants(input),matches=catalog.findReactions(species);if(matches.length===1)return balanceInput(matches[0].equation,matches[0].id);
 const counts={};for(const item of species)for(const[s,n]of Object.entries(item.counts))counts[s]=(counts[s]||0)+n;
 lab.counts=counts;lab.formula=species.map(s=>s.formula).join(' + ');lab.compound=null;lab.dirty=false;lab.balanced=null;lab.reaction=null;lab.charge=species.reduce((a,s)=>a+s.charge,0);lab.candidates=[];lab.reactionChoices=matches;lab.mixture=species;clearError();updateScene();return {reactants:species,matchingReactions:matches.map(r=>({id:r.id,name:r.name,condition:r.condition}))};
}
function renderMixtureResult(){
 $('tray-title').textContent='反應物組成（每種各一份）';$('scene-name').textContent='MIXTURE / 反應物組成示意';
 const matches=lab.reactionChoices;const name=$('result-content').querySelector('.result-name h3'),note=$('result-content').querySelector('.insight p');
 name.textContent=matches.length?'找到 '+matches.length+' 組可能反應':'尚無反應資料';
 note.textContent=matches.length?'相同反應物可以因比例、物態或其他條件而有不同產物，請選擇想了解的情境。':'已解析你加入的物質，但目前沒有收錄這組反應。不能據此判斷不反應或安全；若已知生成物，可輸入完整反應式來檢查守恆。';
 if(matches.length)$('result-content').querySelector('.result-content-inner').insertAdjacentHTML('beforeend',reactionChoices());
}
$('equation-form').addEventListener('submit',e=>{e.preventDefault();try{exploreReactionInput($('equation-input').value)}catch(error){showError(error,'equation-input')}});
function loadReaction(id){let reaction=ChemData.reactions.find(r=>r.id===id);if(!reaction)return;setMode('equation');$('equation-input').value=reaction.equation;if(reaction.prebalanced)loadPrebalanced(reaction);else balanceInput(reaction.equation,reaction.id);$('lab-content').scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderEquationResult(){
 const b=lab.balanced,r=lab.reaction,counts={};for(const item of b.reactants)for(const[s,n]of Object.entries(item.counts))counts[s]=(counts[s]||0n)+BigInt(n)*BigInt(item.coefficient);
 const phase=r?.productState||'unknown';renderer.set(lab.counts,{...lab.compound,state:phase,model:phase==='aqueous'?null:lab.compound?.model});
 $('tray-title').textContent='配平後的反應式';$('atom-chips').innerHTML='<div class="equation-display">'+escapeHTML(equationText(b))+'</div>';$('atom-summary').textContent=b.reactants.length+' 種反應物 · '+b.products.length+' 種生成物';
 $('scene-name').textContent=(r?.participantNames?.products?.find(p=>p.formula===lab.formula)?.name||lab.compound?.name||sub(lab.formula))+' / 生成物示意 · '+stateNames[phase];
 $('result-content').innerHTML=`<div class="result-content-inner"><div class="result-kicker"><span>ATOM CONSERVATION</span><span class="state-badge">已配平</span></div><div class="result-name"><h3>${escapeHTML(r?.name||'原子與電荷守恆')}</h3><span>BALANCED</span></div><div class="result-equation"><small>${r?.prebalanced?'Rhea 來源係數 · 已驗證守恆':'最簡整數係數'}</small>${escapeHTML(equationText(b))}</div><dl class="result-facts">${Object.entries(counts).map(([s,n])=>'<div><dt>'+elementMap[s].name+' '+s+'</dt><dd>'+n.toLocaleString()+' = '+n.toLocaleString()+'</dd></div>').join('')}</dl>
 <div class="insight ${r?.hazard==='unknown'?'warning':r?.hazard||'warning'}"><h4>${escapeHTML(r?.label||'反應是否發生：未知')}</h4><p>${escapeHTML(r?r.note:'配平成功只代表原子和電荷守恆，不表示反應會發生，也不能據此判斷安全性。')}</p></div>
 ${r?.namedEquation?'<div class="named-equation"><small>來源中的物質名稱</small>'+escapeHTML(r.namedEquation)+'</div>':''}${!r?reactionChoices():''}${r?'<p class="result-explanation"><b>'+escapeHTML(r.condition)+'</b><br>'+escapeHTML(r.conclusion)+'</p><button id="play-reaction" class="accent-button reaction-play"><svg><use href="#i-play"/></svg> 播放反應示意</button>'+sourceLink(r.sourceUrl):'<p class="result-explanation">畫面顯示其中一種生成物的組成；未知結構與反應物態保留未知。</p>'}</div>`;
}
let effectTimer;
function playReaction(){if(!lab.reaction)return;renderer.trigger(lab.reaction.effect);$('effect-banner').textContent=lab.reaction.hazard==='danger'?'⚠ '+lab.reaction.label:lab.reaction.effect==='glow'?'✦ 發光與放熱示意':lab.reaction.effect==='heat'?'✦ 放熱示意':lab.reaction.effect==='energy'?'✦ '+lab.reaction.label:'✦ '+lab.reaction.short;$('effect-banner').hidden=false;clearTimeout(effectTimer);effectTimer=setTimeout(()=>$('effect-banner').hidden=true,2300)}
document.querySelectorAll('[data-library]').forEach(b=>b.addEventListener('click',()=>{lab.library=b.dataset.library;libraryState.provenance='all';libraryState.category='all';libraryState.state='all';$('library-state').value='all';libraryState.page=1;libraryState.query='';$('library-search').value='';document.querySelectorAll('[data-library]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});configureLibrary();renderCards()}));
// WebMCP is optional; every action uses the same functions as the visible UI.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};const validInput=input=>{if(!input||typeof input!=='object'||typeof input.formula!=='string')throw new Error('formula 必須是文字');return input.formula};register({name:'inspect_chemistry_lab',description:'讀取目前原子實驗台上的化學式、原子數與模式。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:lab.mode,formula:lab.formula,counts:{...lab.counts},knownCompound:lab.compound?.name||null,equation:lab.balanced?.equation||null})});register({name:'explore_chemical_formula',description:'解析指定化學式，並將可見實驗台切換到化學式探索。不是反應或安全性預測。',inputSchema:{type:'object',properties:{formula:{type:'string'}},required:['formula'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{let value=validInput(input);ChemEngine.parseFormula(value);setMode('formula');$('formula-input').value=value;return exploreFormula(value)}});register({name:'balance_chemical_equation',description:'配平使用者指定的反應物與生成物，更新可見反應式；不判定反應是否會發生。',inputSchema:{type:'object',properties:{equation:{type:'string'}},required:['equation'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.equation!=='string')throw new Error('equation 必須是文字');ChemEngine.balanceEquation(input.equation);setMode('equation');$('equation-input').value=input.equation;return balanceInput(input.equation)}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
configureLibrary();renderElements();renderCards();updateScene();syncPause();
