'use strict';
globalThis.Elements = [
  {
    "number": 1,
    "symbol": "H",
    "name": "氫",
    "english": "Hydrogen",
    "mass": 1.008,
    "period": 1,
    "group": 1,
    "category": "nonmetal",
    "state": "gas",
    "displayRow": 1,
    "displayColumn": 1
  },
  {
    "number": 2,
    "symbol": "He",
    "name": "氦",
    "english": "Helium",
    "mass": 4.0026,
    "period": 1,
    "group": 18,
    "category": "noble",
    "state": "gas",
    "displayRow": 1,
    "displayColumn": 18
  },
  {
    "number": 3,
    "symbol": "Li",
    "name": "鋰",
    "english": "Lithium",
    "mass": 7.0,
    "period": 2,
    "group": 1,
    "category": "alkali",
    "state": "solid",
    "displayRow": 2,
    "displayColumn": 1
  },
  {
    "number": 4,
    "symbol": "Be",
    "name": "鈹",
    "english": "Beryllium",
    "mass": 9.012183,
    "period": 2,
    "group": 2,
    "category": "alkaline",
    "state": "solid",
    "displayRow": 2,
    "displayColumn": 2
  },
  {
    "number": 5,
    "symbol": "B",
    "name": "硼",
    "english": "Boron",
    "mass": 10.81,
    "period": 2,
    "group": 13,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 2,
    "displayColumn": 13
  },
  {
    "number": 6,
    "symbol": "C",
    "name": "碳",
    "english": "Carbon",
    "mass": 12.011,
    "period": 2,
    "group": 14,
    "category": "nonmetal",
    "state": "solid",
    "displayRow": 2,
    "displayColumn": 14
  },
  {
    "number": 7,
    "symbol": "N",
    "name": "氮",
    "english": "Nitrogen",
    "mass": 14.007,
    "period": 2,
    "group": 15,
    "category": "nonmetal",
    "state": "gas",
    "displayRow": 2,
    "displayColumn": 15
  },
  {
    "number": 8,
    "symbol": "O",
    "name": "氧",
    "english": "Oxygen",
    "mass": 15.999,
    "period": 2,
    "group": 16,
    "category": "nonmetal",
    "state": "gas",
    "displayRow": 2,
    "displayColumn": 16
  },
  {
    "number": 9,
    "symbol": "F",
    "name": "氟",
    "english": "Fluorine",
    "mass": 18.99840316,
    "period": 2,
    "group": 17,
    "category": "halogen",
    "state": "gas",
    "displayRow": 2,
    "displayColumn": 17
  },
  {
    "number": 10,
    "symbol": "Ne",
    "name": "氖",
    "english": "Neon",
    "mass": 20.18,
    "period": 2,
    "group": 18,
    "category": "noble",
    "state": "gas",
    "displayRow": 2,
    "displayColumn": 18
  },
  {
    "number": 11,
    "symbol": "Na",
    "name": "鈉",
    "english": "Sodium",
    "mass": 22.9897693,
    "period": 3,
    "group": 1,
    "category": "alkali",
    "state": "solid",
    "displayRow": 3,
    "displayColumn": 1
  },
  {
    "number": 12,
    "symbol": "Mg",
    "name": "鎂",
    "english": "Magnesium",
    "mass": 24.305,
    "period": 3,
    "group": 2,
    "category": "alkaline",
    "state": "solid",
    "displayRow": 3,
    "displayColumn": 2
  },
  {
    "number": 13,
    "symbol": "Al",
    "name": "鋁",
    "english": "Aluminum",
    "mass": 26.981538,
    "period": 3,
    "group": 13,
    "category": "post",
    "state": "solid",
    "displayRow": 3,
    "displayColumn": 13
  },
  {
    "number": 14,
    "symbol": "Si",
    "name": "矽",
    "english": "Silicon",
    "mass": 28.085,
    "period": 3,
    "group": 14,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 3,
    "displayColumn": 14
  },
  {
    "number": 15,
    "symbol": "P",
    "name": "磷",
    "english": "Phosphorus",
    "mass": 30.973762,
    "period": 3,
    "group": 15,
    "category": "nonmetal",
    "state": "solid",
    "displayRow": 3,
    "displayColumn": 15
  },
  {
    "number": 16,
    "symbol": "S",
    "name": "硫",
    "english": "Sulfur",
    "mass": 32.07,
    "period": 3,
    "group": 16,
    "category": "nonmetal",
    "state": "solid",
    "displayRow": 3,
    "displayColumn": 16
  },
  {
    "number": 17,
    "symbol": "Cl",
    "name": "氯",
    "english": "Chlorine",
    "mass": 35.45,
    "period": 3,
    "group": 17,
    "category": "halogen",
    "state": "gas",
    "displayRow": 3,
    "displayColumn": 17
  },
  {
    "number": 18,
    "symbol": "Ar",
    "name": "氬",
    "english": "Argon",
    "mass": 39.9,
    "period": 3,
    "group": 18,
    "category": "noble",
    "state": "gas",
    "displayRow": 3,
    "displayColumn": 18
  },
  {
    "number": 19,
    "symbol": "K",
    "name": "鉀",
    "english": "Potassium",
    "mass": 39.0983,
    "period": 4,
    "group": 1,
    "category": "alkali",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 1
  },
  {
    "number": 20,
    "symbol": "Ca",
    "name": "鈣",
    "english": "Calcium",
    "mass": 40.08,
    "period": 4,
    "group": 2,
    "category": "alkaline",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 2
  },
  {
    "number": 21,
    "symbol": "Sc",
    "name": "鈧",
    "english": "Scandium",
    "mass": 44.95591,
    "period": 4,
    "group": 3,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 3
  },
  {
    "number": 22,
    "symbol": "Ti",
    "name": "鈦",
    "english": "Titanium",
    "mass": 47.867,
    "period": 4,
    "group": 4,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 4
  },
  {
    "number": 23,
    "symbol": "V",
    "name": "釩",
    "english": "Vanadium",
    "mass": 50.9415,
    "period": 4,
    "group": 5,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 5
  },
  {
    "number": 24,
    "symbol": "Cr",
    "name": "鉻",
    "english": "Chromium",
    "mass": 51.996,
    "period": 4,
    "group": 6,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 6
  },
  {
    "number": 25,
    "symbol": "Mn",
    "name": "錳",
    "english": "Manganese",
    "mass": 54.93804,
    "period": 4,
    "group": 7,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 7
  },
  {
    "number": 26,
    "symbol": "Fe",
    "name": "鐵",
    "english": "Iron",
    "mass": 55.84,
    "period": 4,
    "group": 8,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 8
  },
  {
    "number": 27,
    "symbol": "Co",
    "name": "鈷",
    "english": "Cobalt",
    "mass": 58.93319,
    "period": 4,
    "group": 9,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 9
  },
  {
    "number": 28,
    "symbol": "Ni",
    "name": "鎳",
    "english": "Nickel",
    "mass": 58.693,
    "period": 4,
    "group": 10,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 10
  },
  {
    "number": 29,
    "symbol": "Cu",
    "name": "銅",
    "english": "Copper",
    "mass": 63.55,
    "period": 4,
    "group": 11,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 11
  },
  {
    "number": 30,
    "symbol": "Zn",
    "name": "鋅",
    "english": "Zinc",
    "mass": 65.4,
    "period": 4,
    "group": 12,
    "category": "transition",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 12
  },
  {
    "number": 31,
    "symbol": "Ga",
    "name": "鎵",
    "english": "Gallium",
    "mass": 69.723,
    "period": 4,
    "group": 13,
    "category": "post",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 13
  },
  {
    "number": 32,
    "symbol": "Ge",
    "name": "鍺",
    "english": "Germanium",
    "mass": 72.63,
    "period": 4,
    "group": 14,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 14
  },
  {
    "number": 33,
    "symbol": "As",
    "name": "砷",
    "english": "Arsenic",
    "mass": 74.92159,
    "period": 4,
    "group": 15,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 15
  },
  {
    "number": 34,
    "symbol": "Se",
    "name": "硒",
    "english": "Selenium",
    "mass": 78.97,
    "period": 4,
    "group": 16,
    "category": "nonmetal",
    "state": "solid",
    "displayRow": 4,
    "displayColumn": 16
  },
  {
    "number": 35,
    "symbol": "Br",
    "name": "溴",
    "english": "Bromine",
    "mass": 79.9,
    "period": 4,
    "group": 17,
    "category": "halogen",
    "state": "liquid",
    "displayRow": 4,
    "displayColumn": 17
  },
  {
    "number": 36,
    "symbol": "Kr",
    "name": "氪",
    "english": "Krypton",
    "mass": 83.8,
    "period": 4,
    "group": 18,
    "category": "noble",
    "state": "gas",
    "displayRow": 4,
    "displayColumn": 18
  },
  {
    "number": 37,
    "symbol": "Rb",
    "name": "銣",
    "english": "Rubidium",
    "mass": 85.468,
    "period": 5,
    "group": 1,
    "category": "alkali",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 1
  },
  {
    "number": 38,
    "symbol": "Sr",
    "name": "鍶",
    "english": "Strontium",
    "mass": 87.62,
    "period": 5,
    "group": 2,
    "category": "alkaline",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 2
  },
  {
    "number": 39,
    "symbol": "Y",
    "name": "釔",
    "english": "Yttrium",
    "mass": 88.90584,
    "period": 5,
    "group": 3,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 3
  },
  {
    "number": 40,
    "symbol": "Zr",
    "name": "鋯",
    "english": "Zirconium",
    "mass": 91.22,
    "period": 5,
    "group": 4,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 4
  },
  {
    "number": 41,
    "symbol": "Nb",
    "name": "鈮",
    "english": "Niobium",
    "mass": 92.90637,
    "period": 5,
    "group": 5,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 5
  },
  {
    "number": 42,
    "symbol": "Mo",
    "name": "鉬",
    "english": "Molybdenum",
    "mass": 95.95,
    "period": 5,
    "group": 6,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 6
  },
  {
    "number": 43,
    "symbol": "Tc",
    "name": "鎝",
    "english": "Technetium",
    "mass": 96.90636,
    "period": 5,
    "group": 7,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 7
  },
  {
    "number": 44,
    "symbol": "Ru",
    "name": "釕",
    "english": "Ruthenium",
    "mass": 101.1,
    "period": 5,
    "group": 8,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 8
  },
  {
    "number": 45,
    "symbol": "Rh",
    "name": "銠",
    "english": "Rhodium",
    "mass": 102.9055,
    "period": 5,
    "group": 9,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 9
  },
  {
    "number": 46,
    "symbol": "Pd",
    "name": "鈀",
    "english": "Palladium",
    "mass": 106.42,
    "period": 5,
    "group": 10,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 10
  },
  {
    "number": 47,
    "symbol": "Ag",
    "name": "銀",
    "english": "Silver",
    "mass": 107.868,
    "period": 5,
    "group": 11,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 11
  },
  {
    "number": 48,
    "symbol": "Cd",
    "name": "鎘",
    "english": "Cadmium",
    "mass": 112.41,
    "period": 5,
    "group": 12,
    "category": "transition",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 12
  },
  {
    "number": 49,
    "symbol": "In",
    "name": "銦",
    "english": "Indium",
    "mass": 114.818,
    "period": 5,
    "group": 13,
    "category": "post",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 13
  },
  {
    "number": 50,
    "symbol": "Sn",
    "name": "錫",
    "english": "Tin",
    "mass": 118.71,
    "period": 5,
    "group": 14,
    "category": "post",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 14
  },
  {
    "number": 51,
    "symbol": "Sb",
    "name": "銻",
    "english": "Antimony",
    "mass": 121.76,
    "period": 5,
    "group": 15,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 15
  },
  {
    "number": 52,
    "symbol": "Te",
    "name": "碲",
    "english": "Tellurium",
    "mass": 127.6,
    "period": 5,
    "group": 16,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 16
  },
  {
    "number": 53,
    "symbol": "I",
    "name": "碘",
    "english": "Iodine",
    "mass": 126.9045,
    "period": 5,
    "group": 17,
    "category": "halogen",
    "state": "solid",
    "displayRow": 5,
    "displayColumn": 17
  },
  {
    "number": 54,
    "symbol": "Xe",
    "name": "氙",
    "english": "Xenon",
    "mass": 131.29,
    "period": 5,
    "group": 18,
    "category": "noble",
    "state": "gas",
    "displayRow": 5,
    "displayColumn": 18
  },
  {
    "number": 55,
    "symbol": "Cs",
    "name": "銫",
    "english": "Cesium",
    "mass": 132.905452,
    "period": 6,
    "group": 1,
    "category": "alkali",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 1
  },
  {
    "number": 56,
    "symbol": "Ba",
    "name": "鋇",
    "english": "Barium",
    "mass": 137.33,
    "period": 6,
    "group": 2,
    "category": "alkaline",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 2
  },
  {
    "number": 57,
    "symbol": "La",
    "name": "鑭",
    "english": "Lanthanum",
    "mass": 138.9055,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 4
  },
  {
    "number": 58,
    "symbol": "Ce",
    "name": "鈰",
    "english": "Cerium",
    "mass": 140.116,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 5
  },
  {
    "number": 59,
    "symbol": "Pr",
    "name": "鐠",
    "english": "Praseodymium",
    "mass": 140.90766,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 6
  },
  {
    "number": 60,
    "symbol": "Nd",
    "name": "釹",
    "english": "Neodymium",
    "mass": 144.24,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 7
  },
  {
    "number": 61,
    "symbol": "Pm",
    "name": "鉕",
    "english": "Promethium",
    "mass": 144.91276,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 8
  },
  {
    "number": 62,
    "symbol": "Sm",
    "name": "釤",
    "english": "Samarium",
    "mass": 150.4,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 9
  },
  {
    "number": 63,
    "symbol": "Eu",
    "name": "銪",
    "english": "Europium",
    "mass": 151.964,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 10
  },
  {
    "number": 64,
    "symbol": "Gd",
    "name": "釓",
    "english": "Gadolinium",
    "mass": 157.25,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 11
  },
  {
    "number": 65,
    "symbol": "Tb",
    "name": "鋱",
    "english": "Terbium",
    "mass": 158.92535,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 12
  },
  {
    "number": 66,
    "symbol": "Dy",
    "name": "鏑",
    "english": "Dysprosium",
    "mass": 162.5,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 13
  },
  {
    "number": 67,
    "symbol": "Ho",
    "name": "鈥",
    "english": "Holmium",
    "mass": 164.93033,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 14
  },
  {
    "number": 68,
    "symbol": "Er",
    "name": "鉺",
    "english": "Erbium",
    "mass": 167.26,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 15
  },
  {
    "number": 69,
    "symbol": "Tm",
    "name": "銩",
    "english": "Thulium",
    "mass": 168.93422,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 16
  },
  {
    "number": 70,
    "symbol": "Yb",
    "name": "鐿",
    "english": "Ytterbium",
    "mass": 173.05,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 17
  },
  {
    "number": 71,
    "symbol": "Lu",
    "name": "鎦",
    "english": "Lutetium",
    "mass": 174.9667,
    "period": 6,
    "group": null,
    "category": "lanthanide",
    "state": "solid",
    "displayRow": 8,
    "displayColumn": 18
  },
  {
    "number": 72,
    "symbol": "Hf",
    "name": "鉿",
    "english": "Hafnium",
    "mass": 178.49,
    "period": 6,
    "group": 4,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 4
  },
  {
    "number": 73,
    "symbol": "Ta",
    "name": "鉭",
    "english": "Tantalum",
    "mass": 180.9479,
    "period": 6,
    "group": 5,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 5
  },
  {
    "number": 74,
    "symbol": "W",
    "name": "鎢",
    "english": "Tungsten",
    "mass": 183.84,
    "period": 6,
    "group": 6,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 6
  },
  {
    "number": 75,
    "symbol": "Re",
    "name": "錸",
    "english": "Rhenium",
    "mass": 186.207,
    "period": 6,
    "group": 7,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 7
  },
  {
    "number": 76,
    "symbol": "Os",
    "name": "鋨",
    "english": "Osmium",
    "mass": 190.2,
    "period": 6,
    "group": 8,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 8
  },
  {
    "number": 77,
    "symbol": "Ir",
    "name": "銥",
    "english": "Iridium",
    "mass": 192.22,
    "period": 6,
    "group": 9,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 9
  },
  {
    "number": 78,
    "symbol": "Pt",
    "name": "鉑",
    "english": "Platinum",
    "mass": 195.08,
    "period": 6,
    "group": 10,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 10
  },
  {
    "number": 79,
    "symbol": "Au",
    "name": "金",
    "english": "Gold",
    "mass": 196.96657,
    "period": 6,
    "group": 11,
    "category": "transition",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 11
  },
  {
    "number": 80,
    "symbol": "Hg",
    "name": "汞",
    "english": "Mercury",
    "mass": 200.59,
    "period": 6,
    "group": 12,
    "category": "transition",
    "state": "liquid",
    "displayRow": 6,
    "displayColumn": 12
  },
  {
    "number": 81,
    "symbol": "Tl",
    "name": "鉈",
    "english": "Thallium",
    "mass": 204.383,
    "period": 6,
    "group": 13,
    "category": "post",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 13
  },
  {
    "number": 82,
    "symbol": "Pb",
    "name": "鉛",
    "english": "Lead",
    "mass": 207.0,
    "period": 6,
    "group": 14,
    "category": "post",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 14
  },
  {
    "number": 83,
    "symbol": "Bi",
    "name": "鉍",
    "english": "Bismuth",
    "mass": 208.9804,
    "period": 6,
    "group": 15,
    "category": "post",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 15
  },
  {
    "number": 84,
    "symbol": "Po",
    "name": "釙",
    "english": "Polonium",
    "mass": 208.98243,
    "period": 6,
    "group": 16,
    "category": "metalloid",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 16
  },
  {
    "number": 85,
    "symbol": "At",
    "name": "砈",
    "english": "Astatine",
    "mass": 209.98715,
    "period": 6,
    "group": 17,
    "category": "halogen",
    "state": "solid",
    "displayRow": 6,
    "displayColumn": 17
  },
  {
    "number": 86,
    "symbol": "Rn",
    "name": "氡",
    "english": "Radon",
    "mass": 222.01758,
    "period": 6,
    "group": 18,
    "category": "noble",
    "state": "gas",
    "displayRow": 6,
    "displayColumn": 18
  },
  {
    "number": 87,
    "symbol": "Fr",
    "name": "鍅",
    "english": "Francium",
    "mass": 223.01973,
    "period": 7,
    "group": 1,
    "category": "alkali",
    "state": "solid",
    "displayRow": 7,
    "displayColumn": 1
  },
  {
    "number": 88,
    "symbol": "Ra",
    "name": "鐳",
    "english": "Radium",
    "mass": 226.02541,
    "period": 7,
    "group": 2,
    "category": "alkaline",
    "state": "solid",
    "displayRow": 7,
    "displayColumn": 2
  },
  {
    "number": 89,
    "symbol": "Ac",
    "name": "錒",
    "english": "Actinium",
    "mass": 227.02775,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 4
  },
  {
    "number": 90,
    "symbol": "Th",
    "name": "釷",
    "english": "Thorium",
    "mass": 232.038,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 5
  },
  {
    "number": 91,
    "symbol": "Pa",
    "name": "鏷",
    "english": "Protactinium",
    "mass": 231.03588,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 6
  },
  {
    "number": 92,
    "symbol": "U",
    "name": "鈾",
    "english": "Uranium",
    "mass": 238.0289,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 7
  },
  {
    "number": 93,
    "symbol": "Np",
    "name": "錼",
    "english": "Neptunium",
    "mass": 237.048172,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 8
  },
  {
    "number": 94,
    "symbol": "Pu",
    "name": "鈽",
    "english": "Plutonium",
    "mass": 244.0642,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 9
  },
  {
    "number": 95,
    "symbol": "Am",
    "name": "鋂",
    "english": "Americium",
    "mass": 243.06138,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 10
  },
  {
    "number": 96,
    "symbol": "Cm",
    "name": "鋦",
    "english": "Curium",
    "mass": 247.07035,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 11
  },
  {
    "number": 97,
    "symbol": "Bk",
    "name": "鉳",
    "english": "Berkelium",
    "mass": 247.07031,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 12
  },
  {
    "number": 98,
    "symbol": "Cf",
    "name": "鉲",
    "english": "Californium",
    "mass": 251.07959,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 13
  },
  {
    "number": 99,
    "symbol": "Es",
    "name": "鑀",
    "english": "Einsteinium",
    "mass": 252.083,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 14
  },
  {
    "number": 100,
    "symbol": "Fm",
    "name": "鐨",
    "english": "Fermium",
    "mass": 257.09511,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 15
  },
  {
    "number": 101,
    "symbol": "Md",
    "name": "鍆",
    "english": "Mendelevium",
    "mass": 258.09843,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 16
  },
  {
    "number": 102,
    "symbol": "No",
    "name": "鍩",
    "english": "Nobelium",
    "mass": 259.101,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 17
  },
  {
    "number": 103,
    "symbol": "Lr",
    "name": "鐒",
    "english": "Lawrencium",
    "mass": 266.12,
    "period": 7,
    "group": null,
    "category": "actinide",
    "state": "solid",
    "displayRow": 9,
    "displayColumn": 18
  },
  {
    "number": 104,
    "symbol": "Rf",
    "name": "鑪",
    "english": "Rutherfordium",
    "mass": 267.122,
    "period": 7,
    "group": 4,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 4
  },
  {
    "number": 105,
    "symbol": "Db",
    "name": "𨧀",
    "english": "Dubnium",
    "mass": 268.126,
    "period": 7,
    "group": 5,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 5
  },
  {
    "number": 106,
    "symbol": "Sg",
    "name": "𨭎",
    "english": "Seaborgium",
    "mass": 269.128,
    "period": 7,
    "group": 6,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 6
  },
  {
    "number": 107,
    "symbol": "Bh",
    "name": "𨨏",
    "english": "Bohrium",
    "mass": 270.133,
    "period": 7,
    "group": 7,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 7
  },
  {
    "number": 108,
    "symbol": "Hs",
    "name": "𨭆",
    "english": "Hassium",
    "mass": 269.1336,
    "period": 7,
    "group": 8,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 8
  },
  {
    "number": 109,
    "symbol": "Mt",
    "name": "䥑",
    "english": "Meitnerium",
    "mass": 277.154,
    "period": 7,
    "group": 9,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 9
  },
  {
    "number": 110,
    "symbol": "Ds",
    "name": "鐽",
    "english": "Darmstadtium",
    "mass": 282.166,
    "period": 7,
    "group": 10,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 10
  },
  {
    "number": 111,
    "symbol": "Rg",
    "name": "錀",
    "english": "Roentgenium",
    "mass": 282.169,
    "period": 7,
    "group": 11,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 11
  },
  {
    "number": 112,
    "symbol": "Cn",
    "name": "鎶",
    "english": "Copernicium",
    "mass": 286.179,
    "period": 7,
    "group": 12,
    "category": "transition",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 12
  },
  {
    "number": 113,
    "symbol": "Nh",
    "name": "鉨",
    "english": "Nihonium",
    "mass": 286.182,
    "period": 7,
    "group": 13,
    "category": "post",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 13
  },
  {
    "number": 114,
    "symbol": "Fl",
    "name": "鈇",
    "english": "Flerovium",
    "mass": 290.192,
    "period": 7,
    "group": 14,
    "category": "post",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 14
  },
  {
    "number": 115,
    "symbol": "Mc",
    "name": "鏌",
    "english": "Moscovium",
    "mass": 290.196,
    "period": 7,
    "group": 15,
    "category": "post",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 15
  },
  {
    "number": 116,
    "symbol": "Lv",
    "name": "鉝",
    "english": "Livermorium",
    "mass": 293.205,
    "period": 7,
    "group": 16,
    "category": "post",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 16
  },
  {
    "number": 117,
    "symbol": "Ts",
    "name": "鿬",
    "english": "Tennessine",
    "mass": 294.211,
    "period": 7,
    "group": 17,
    "category": "halogen",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 17
  },
  {
    "number": 118,
    "symbol": "Og",
    "name": "鿫",
    "english": "Oganesson",
    "mass": 295.216,
    "period": 7,
    "group": 18,
    "category": "noble",
    "state": "unknown",
    "displayRow": 7,
    "displayColumn": 18
  }
]
;